apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    k8s-app: prometheus 
spec:
  selector: 
    k8s-app: prometheus
  type: NodePort  
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP
