---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: querier
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: querier
    spec:
      containers:
      - name: querier
        image: mjsjinsu/querier:201802
        imagePullPolicy: IfNotPresent
        args:
        - -server.http-listen-port=80
        - -consul.hostname=consul.monitoring.svc.cluster.local:8500
        - -querier.frontend-address=query-frontend.monitoring.svc.cluster.local:9095
        - -chunk.storage-client=cassandra
        - -cassandra.addresses=cassandra.monitoring.svc.cluster.local:9042
        - -cassandra.keyspace=cortex
        - -cassandra.host-verification=false
        - -memcached.hostname=memcached.monitoring.svc.cluster.local
        - -memcached.timeout=100ms
        - -memcached.service=memcached
        - -distributor.replication-factor=1
        ports:
        - containerPort: 80
