---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: table-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: table-manager
    spec:
      containers:
      - name: table-manager
        image: mjsjinsu/table-manager:20190322
        imagePullPolicy: IfNotPresent
        args:
        - -server.http-listen-port=80
        - -chunk.storage-client=cassandra
        - -cassandra.addresses=cassandra.monitoring.svc.cluster.local:9042
        - -cassandra.keyspace=cortex
        - -cassandra.host-verification=false
        - -cassandra.timeout=2000m
        - -dynamodb.periodic-table.prefix=cortex_weekly_
        - -dynamodb.periodic-table.from=2019-01-01
        - -dynamodb.original-table-name=cortex
        - -dynamodb.daily-buckets-from=2019-01-01
        - -dynamodb.base64-buckets-from=2019-01-01
        - -dynamodb.v6-schema-from=2019-01-01
        - -dynamodb.use-periodic-tables=true
        - -dynamodb.chunk-table.from=2019-01-01
        ports:
        - containerPort: 80
