apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-0 
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: /opt/cassandra-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 172.17.1.125
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: /opt/cassandra-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 172.17.1.136 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: /opt/cassandra-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 172.17.1.89
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
